### ISSUE TITLE
[CI] 参照 blocklet-registry 实现自动化的 CI 流程

### ISSUE THREAD

**Issue by wangshijun** [blocklet/install-on-abtnode#6]
要点

- 使用 github actions
- 把这个 repo 设置为 public，不然无法使用全局的环境变量
- CI 里面要做的事情是打包、发布到 npm、部署到 production 节点

自动化是一个项目迭代效率的基本保障

**Comment by leermao** [comment]
> 要点
> 
> * 使用 github actions
> * 把这个 repo 设置为 public，不然无法使用全局的环境变量
> * CI 里面要做的事情是打包、发布到 npm、部署到 production 节点
> 
> 自动化是一个项目迭代效率的基本保障

想想就开心  自动化是自己很想看的部分

**Comment by wangshijun** [comment]
https://www.npmjs.com/package/install-on-abtnode
